VIT:
  PROJECT:
    name: "pokemon-classification-vit"
  MODEL:
    d_model: 64
    patch_size: 16
    n_channels: 3
    n_heads: 8
    n_layers: 6

CNN:
  PROJECT:
    name: "pokemon-classification-cnn"


TRAIN:
  n_classes: 5
  epochs: 50
  batch_size: 24
  lr: 0.001
  weight_decay: 1e-4
  img_size: 240
  seed: 42
VAL:
  batch_size: 24

LOCAL:
  train_dir: "resnet-vit-comparison/data/train"
  val_dir: "resnet-vit-comparison/data/val"  
  output_dir: "resnet-vit-comparison/results"
  check_point_dir: "resnet-vit-comparison/results/checkpoints"



