VIT:
  PROJECT:
    name: "pokemon-classification-vit"
  MODEL:
    learning_rate: 0.0001
    d_model: 192
    patch_size: 16
    n_channels: 3
    n_heads: 6
    n_layers: 12
    weight_decay: 1e-4
    dropout: 0.5
CNN:
  PROJECT:
    name: "pokemon-classification-cnn"
  MODEL:
    learning_rate: 0.0002
    weight_decay: 1e-5
    dropout: 0.6
    scheduler_step: 15
    scheduler_factor: 0.7

TRAIN:
  n_classes: 5
  epochs: 30
  batch_size: 32
  img_size: 192
  seed: 42
VAL:
  batch_size: 64

LOCAL:
  train_dir: "resnet-vit-comparison/data/train"
  val_dir: "resnet-vit-comparison/data/val"  
  output_dir: "resnet-vit-comparison/results"
  check_point_dir: "resnet-vit-comparison/results/checkpoints"



