PROJECT:
  name: "pokemon-classification-cnn"

MODEL:
  n_classes: 5
  img_size: 240

TRAIN:
  epochs: 25
  batch_size: 24
  lr: 0.001
  weight_decay: 1e-4
  
VAL:
  batch_size: 24

LOCAL:
  train_dir: "../data/train"
  val_dir: "../data/val"  
  output_dir: "results"
  check_point_dir: "checkpoints"