MODEL:
  d_model: 9
  n_classes: 5
  img_size: 640
  patch_size: 16
  n_channels: 1
  n_heads: 3
  n_layers: 3

TRAIN:
  epochs: 10
  batch_size: 24
  lr: 0.001

VAL:
  batch_size: 24

LOCAL:
  train_dir: "data/train"
  val_dir: "data/val"  
  output_dir: "results"
  check_point_dir: "checkpoints"
